/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author PICHAU
 */
public class Pedido extends javax.swing.JFrame {

    /**
     * Creates new form PessoFisica
     */
    public Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnSair = new javax.swing.JToggleButton();
        btnFazerPedido = new javax.swing.JToggleButton();
        btnConsultarStatus1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo (1).png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(180, 20, 450, 200);

        btnSair.setSelected(true);
        btnSair.setText("Sair");
        btnSair.setActionCommand("");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(290, 570, 150, 60);

        btnFazerPedido.setSelected(true);
        btnFazerPedido.setText("Fazer Pedido");
        btnFazerPedido.setActionCommand("Consultar");
        btnFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFazerPedido);
        btnFazerPedido.setBounds(250, 260, 260, 80);

        btnConsultarStatus1.setSelected(true);
        btnConsultarStatus1.setText("Consultar Status");
        btnConsultarStatus1.setActionCommand("");
        btnConsultarStatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarStatus1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarStatus1);
        btnConsultarStatus1.setBounds(250, 380, 270, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 700);

        setSize(new java.awt.Dimension(766, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerPedidoActionPerformed
        // TODO add your handling code here:
        new RealizarPedido().setVisible(true);
    }//GEN-LAST:event_btnFazerPedidoActionPerformed

    private void btnConsultarStatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarStatus1ActionPerformed
        // TODO add your handling code here:
        new StatusPedido().setVisible(true);
    }//GEN-LAST:event_btnConsultarStatus1ActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {*/
            public void run() {
                new Pedido().setVisible(true);
            }
       /* });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConsultarStatus1;
    private javax.swing.JToggleButton btnFazerPedido;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
