/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import javax.swing.JOptionPane;
import model.Cliente;
import model.ClientePJ;

/**
 *
 * @author PICHAU
 */
public class PessoJuridica extends javax.swing.JFrame {

    /**
     * Creates new form PessoFisica
     */
    public PessoJuridica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jNumero = new javax.swing.JTextField();
        jEstado = new javax.swing.JTextField();
        jBairro = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        jRazaoSocial = new javax.swing.JTextField();
        jCEP = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jRua = new javax.swing.JTextField();
        jComplemento = new javax.swing.JTextField();
        jNomeFantasia = new javax.swing.JTextField();
        jCNPJ = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jTelefone = new javax.swing.JTextField();
        jSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        jLabel1.setText("E-mail");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 80, 47, 14);

        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 120, 47, 14);

        jLabel3.setText("CNPJ:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 160, 47, 14);

        jLabel4.setText("Nome Fantasia:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 200, 90, 14);

        jLabel5.setText("Razão Social:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 240, 82, 14);

        jLabel6.setText("CEP:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 340, 39, 14);

        jLabel7.setText("Cidade:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 380, 56, 14);

        jLabel8.setText("Rua:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 420, 45, 14);

        jLabel9.setText("Bairro:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 460, 45, 14);

        jLabel10.setText("Estado:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 500, 56, 14);

        jLabel11.setText("Numero:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 540, 70, 14);

        jLabel12.setText("Telefone:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 290, 82, 14);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel13.setText("Pessoa Jurídica");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(260, 20, 190, 30);

        jNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jNumero);
        jNumero.setBounds(130, 530, 510, 30);
        jPanel1.add(jEstado);
        jEstado.setBounds(130, 490, 510, 30);
        jPanel1.add(jBairro);
        jBairro.setBounds(130, 450, 510, 30);

        JEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmailActionPerformed(evt);
            }
        });
        jPanel1.add(JEmail);
        JEmail.setBounds(130, 70, 510, 30);
        jPanel1.add(jRazaoSocial);
        jRazaoSocial.setBounds(130, 230, 510, 30);
        jPanel1.add(jCEP);
        jCEP.setBounds(130, 330, 510, 30);
        jPanel1.add(jCidade);
        jCidade.setBounds(130, 370, 510, 30);
        jPanel1.add(jRua);
        jRua.setBounds(130, 410, 510, 30);

        jComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComplementoActionPerformed(evt);
            }
        });
        jPanel1.add(jComplemento);
        jComplemento.setBounds(130, 570, 510, 30);
        jPanel1.add(jNomeFantasia);
        jNomeFantasia.setBounds(130, 190, 510, 30);
        jPanel1.add(jCNPJ);
        jCNPJ.setBounds(130, 150, 510, 30);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(330, 620, 100, 30);

        jLabel14.setText("Complemento:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 580, 82, 14);

        jTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jTelefone);
        jTelefone.setBounds(130, 280, 510, 30);
        jPanel1.add(jSenha);
        jSenha.setBounds(130, 110, 510, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 700);

        setSize(new java.awt.Dimension(766, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComplementoActionPerformed

    private void JEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEmailActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if(JEmail.getText() != null && JEmail.getText().length() > 0 && jSenha.getPassword() != null &&  jSenha.getPassword().length > 0 && jCNPJ.getText() != null && jCNPJ.getText().length() > 0  && jNomeFantasia.getText() != null && jNomeFantasia.getText().length() > 0 
                && jRazaoSocial.getText() != null  && jRazaoSocial.getText().length() > 0 && jTelefone.getText() != null && jTelefone.getText().length() > 0 && jCEP.getText() != null && jCEP.getText().length() > 0 && jCidade.getText() != null && 
                jCidade.getText().length() > 0 && jRua.getText() != null && jRua.getText().length() > 0 && jBairro.getText() != null && jBairro.getText().length() > 0 && jEstado.getText() != null && jEstado.getText().length() > 0 && jNumero.getText() != null
                && jNumero.getText().length() > 0 && jComplemento.getText() != null && jComplemento.getText().length() > 0 ){
            
            
            String senha = new String (jSenha.getPassword());
            Integer numero = Integer.parseInt(jNumero.getText());
            Integer telefone = Integer.parseInt(jTelefone.getText());
            Integer complemento = Integer.parseInt(jComplemento.getText());
            
            ClientePJ clientepj = new ClientePJ(jCNPJ.getText(),jNomeFantasia.getText(), jRazaoSocial.getText(),JEmail.getText(), jRua.getText(), numero, complemento, jBairro.getText(), jCidade.getText(), jEstado.getText(), jCEP.getText(), senha, telefone);
            
            ClienteController controler = new ClienteController();
            controler.casdastrarClientePJ(clientepj);
            
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void jTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTelefoneActionPerformed

    private void jNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoJuridica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {*/
            public void run() {
                new PessoJuridica().setVisible(true);
            }
       /* });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JEmail;
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JTextField jBairro;
    private javax.swing.JTextField jCEP;
    private javax.swing.JTextField jCNPJ;
    private javax.swing.JTextField jCidade;
    private javax.swing.JTextField jComplemento;
    private javax.swing.JTextField jEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNomeFantasia;
    private javax.swing.JTextField jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jRazaoSocial;
    private javax.swing.JTextField jRua;
    private javax.swing.JPasswordField jSenha;
    private javax.swing.JTextField jTelefone;
    // End of variables declaration//GEN-END:variables
}
