/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PedidoController;
import model.Detalhes_pedido;
import model.Entrega;
import model.Pagamento;
import model.Produto;

/**
 *
 * @author PICHAU
 */
public class RealizarPedido extends javax.swing.JFrame {

    /**
     * Creates new form PessoFisica
     */
    public RealizarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jQuantidade = new javax.swing.JTextField();
        btnFazerPedido = new javax.swing.JToggleButton();
        jComboBoxTamanho = new javax.swing.JComboBox<>();
        jComboBoxTipoEntrega = new javax.swing.JComboBox<>();
        jValorTotal = new javax.swing.JTextField();
        btnFazerPedido3 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jButtonVerificarValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        jLabel1.setText("Produto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 160, 47, 14);

        jLabel2.setText("Tamanho:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 210, 80, 14);

        jLabel3.setText("Quantidade:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 260, 80, 14);

        jLabel4.setText("Valor Total:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 310, 90, 14);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel13.setText("Pedido");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 60, 190, 30);
        jPanel1.add(jQuantidade);
        jQuantidade.setBounds(150, 250, 490, 30);

        btnFazerPedido.setText("Fazer Pedido");
        btnFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFazerPedido);
        btnFazerPedido.setBounds(400, 550, 110, 50);

        jComboBoxTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeno" }));
        jComboBoxTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamanhoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTamanho);
        jComboBoxTamanho.setBounds(150, 200, 490, 30);

        jComboBoxTipoEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retirada", "A combinar" }));
        jComboBoxTipoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEntregaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxTipoEntrega);
        jComboBoxTipoEntrega.setBounds(150, 450, 490, 30);

        jValorTotal.setEnabled(false);
        jPanel1.add(jValorTotal);
        jValorTotal.setBounds(150, 300, 490, 30);

        btnFazerPedido3.setText("Voltar");
        btnFazerPedido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerPedido3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnFazerPedido3);
        btnFazerPedido3.setBounds(150, 550, 110, 50);

        jLabel5.setText("Forma de pagamento:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 400, 110, 14);

        jLabel6.setText("Tipo entrega:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 460, 70, 14);

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolos de caixa", "Bolo Vulcão", "Chocolate", "Mini Naked", "Brownie" }));
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProduto);
        jComboBoxProduto.setBounds(150, 150, 490, 30);

        jComboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão" }));
        jComboBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaPagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxFormaPagamento);
        jComboBoxFormaPagamento.setBounds(150, 390, 490, 30);

        jButtonVerificarValor.setText("Verificar Valor Total");
        jButtonVerificarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarValorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVerificarValor);
        jButtonVerificarValor.setBounds(470, 340, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 700);

        setSize(new java.awt.Dimension(766, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerPedidoActionPerformed
        // TODO add your handling code here:
        
         String produto = jComboBoxTipoEntrega.getSelectedItem().toString().trim();
         String tamanho = jComboBoxTamanho.getSelectedItem().toString().trim();
         String forma_pagamento = jComboBoxFormaPagamento.getSelectedItem().toString().trim();
         String tipo_entrega = jComboBoxTipoEntrega.getSelectedItem().toString().trim();
                  
         if(jQuantidade.getText() != null && jQuantidade.getText().length() > 0 
            && produto != null && produto.length() > 0 &&  tamanho != null && tamanho.length() > 0 
            && forma_pagamento != null && forma_pagamento.length() > 0 && tipo_entrega != null && 
            tipo_entrega.length() > 0 ){             
             
             Float valor = Float.parseFloat(jValorTotal.getText());
             Integer quantidade = Integer.parseInt(jQuantidade.getText());
             
                  //produtos
             model.Produto Mproduto = new Produto();
             Mproduto.setProduto_nome(produto);
             Mproduto.setTamanho(tamanho);        
             
             //entrega 
             Entrega entrega = new Entrega();
             if(tipo_entrega.equals("Retirada")){
                 
                 entrega.setEntrega_id(1);
                 
             } else if(tipo_entrega.equals("A combinar")){
                 entrega.setEntrega_id(2);
             }
             
             //pagamento
             Pagamento pagamento = new Pagamento();
             if(forma_pagamento.equals("Dinheiro")){
                 
                 pagamento.setPagamento_id(1);
                 
             } else if(forma_pagamento.equals("Cartão")){
                 pagamento.setPagamento_id(2);
             }             
                
             
             //detalhes do pedido
             model.Detalhes_pedido dp = new Detalhes_pedido();
             dp.setQuantidade(quantidade);
             
             model.Pedido pedido = new model.Pedido();
             pedido.setStatus_pedido("Em preparação");
          
                         
             PedidoController pc = new PedidoController();
             pc.realizarPedido(pagamento, entrega, pedido);
             
             
         }
        
        
    }//GEN-LAST:event_btnFazerPedidoActionPerformed

    private void jComboBoxTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamanhoActionPerformed

    private void jComboBoxTipoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoEntregaActionPerformed

    private void btnFazerPedido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerPedido3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFazerPedido3ActionPerformed

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void jComboBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFormaPagamentoActionPerformed

    private void jButtonVerificarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarValorActionPerformed
        // TODO add your handling code here:
        
        String produto = jComboBoxProduto.getSelectedItem().toString().trim();
         String tamanho = jComboBoxTamanho.getSelectedItem().toString().trim();
        
              
         if(jQuantidade.getText() != null && jQuantidade.getText().length() > 0  && produto != null && 
                 produto.length() > 0 && tamanho != null && tamanho.length() > 0 ){             
             
         
             Integer quantidade = Integer.parseInt(jQuantidade.getText());
             
                  //produtos
             model.Produto Mproduto = new Produto();
             Mproduto.setProduto_nome(produto);
             Mproduto.setTamanho(tamanho);        
             
             
                      
                 
            
             
             
             //detalhes do pedido
             model.Detalhes_pedido dp = new Detalhes_pedido();
             dp.setQuantidade(quantidade);
           
             
             PedidoController pc = new PedidoController();
             
             
            Float  valor1 =  pc.pegarValor(Mproduto, dp);
            
            jValorTotal.setText(valor1.toString());
         } 
        
    }//GEN-LAST:event_jButtonVerificarValorActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {*/
            public void run() {
                new RealizarPedido().setVisible(true);
            }
       /* });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFazerPedido;
    private javax.swing.JToggleButton btnFazerPedido3;
    private javax.swing.JButton jButtonVerificarValor;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JComboBox<String> jComboBoxTamanho;
    private javax.swing.JComboBox<String> jComboBoxTipoEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQuantidade;
    private javax.swing.JTextField jValorTotal;
    // End of variables declaration//GEN-END:variables
}
