/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PedidoController;
import dao.PedidoDao;
import model.Pedido;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PICHAU
 */
public class StatusPedido extends javax.swing.JFrame {

    /**
     * Creates new form PessoFisica
     */
    public StatusPedido() {
        initComponents();
        
        exibirPedidos();
    }

    public void exibirPedidos(){
        DefaultTableModel modelo = (DefaultTableModel) jTableStatusPedido.getModel();
        modelo.setNumRows(0);
        PedidoDao dao  = new PedidoDao();
        
        for (Pedido p: dao.consultarPedido()){
            modelo.addRow(new Object[]{
            
            p.getPedido_id(),
            p.getStatus_pedido(),
            p.getData_pedido(),
            p.getData_entrega()
            
        });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStatusPedido = new javax.swing.JTable();
        jButtonExcluirPedido = new javax.swing.JButton();
        jButtonAlterarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel13.setText("Status - Pedido");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(250, 20, 270, 50);

        btnVoltar.setSelected(true);
        btnVoltar.setText("Voltar");
        btnVoltar.setActionCommand("Consultar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(630, 20, 100, 40);

        jTableStatusPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do Pedido", "Status do Pedido", "Data do Pedido", "Data da Entrega"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableStatusPedido);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 730, 460);

        jButtonExcluirPedido.setText("Excluir Pedido");
        jButtonExcluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluirPedido);
        jButtonExcluirPedido.setBounds(480, 170, 110, 30);

        jButtonAlterarPedido.setText("Alterar Pedido");
        jButtonAlterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAlterarPedido);
        jButtonAlterarPedido.setBounds(600, 170, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 700);

        setSize(new java.awt.Dimension(766, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jButtonExcluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirPedidoActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model1 = (DefaultTableModel) jTableStatusPedido.getModel();
        int selecionarLinha = jTableStatusPedido.getSelectedRow();
        
        Pedido pedido= new Pedido();
        String id;
        id = model1.getValueAt(selecionarLinha, 0).toString();
        pedido.setPedido_id(Integer.parseInt(id));
        pedido.setStatus_pedido(model1.getValueAt(selecionarLinha, 1).toString());
        
        
        
        
        PedidoController pedidoControler = new PedidoController();
        
        pedidoControler.excluirPedido(pedido);
        
    }//GEN-LAST:event_jButtonExcluirPedidoActionPerformed

    private void jButtonAlterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarPedidoActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButtonAlterarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {*/
            public void run() {
                new StatusPedido().setVisible(true);
            }
        /*});
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JButton jButtonAlterarPedido;
    private javax.swing.JButton jButtonExcluirPedido;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStatusPedido;
    // End of variables declaration//GEN-END:variables
}
