/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confeitaria.view;

import confeitaria.controller.ClienteController;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Max
 */
public class TelaCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_Tela_Cadastro_Cliente = new javax.swing.JLabel();
        jPanel2_Cadastro_Cliente = new javax.swing.JPanel();
        jLabel1_Email = new javax.swing.JLabel();
        jTextField1_Email = new javax.swing.JTextField();
        jLabel2_Tipo_Pessoa = new javax.swing.JLabel();
        jComboBox1_Tipo_Pessoa = new javax.swing.JComboBox<>();
        jLabel3_CPF = new javax.swing.JLabel();
        jTextField3_CPF = new javax.swing.JTextField();
        jLabel4_Nome = new javax.swing.JLabel();
        jTextField4_Nome = new javax.swing.JTextField();
        jLabel5_Sobrenome = new javax.swing.JLabel();
        jTextField5_Sobrenome = new javax.swing.JTextField();
        jLabel6_CNPJ = new javax.swing.JLabel();
        jTextField6_CNPJ = new javax.swing.JTextField();
        jLabel7_Razão_Social = new javax.swing.JLabel();
        jTextField7_Razão_Social = new javax.swing.JTextField();
        jLabel8_Nome_Fantasia = new javax.swing.JLabel();
        jTextField8_Nome_Fantasia = new javax.swing.JTextField();
        jLabel9_Rua = new javax.swing.JLabel();
        jTextField9_Rua = new javax.swing.JTextField();
        jLabel10_Número = new javax.swing.JLabel();
        jTextField10_Número = new javax.swing.JTextField();
        jLabel11_Complemento = new javax.swing.JLabel();
        jTextField11_Complemento = new javax.swing.JTextField();
        jLabel12_Bairro = new javax.swing.JLabel();
        jTextField12_Bairro = new javax.swing.JTextField();
        jLabel13_Cidade = new javax.swing.JLabel();
        jTextField13_Cidade = new javax.swing.JTextField();
        jLabel14_Estado = new javax.swing.JLabel();
        jTextField14_Estado = new javax.swing.JTextField();
        jLabel15_CEP = new javax.swing.JLabel();
        jTextField15_CEP = new javax.swing.JTextField();
        jButton1_Salvar = new javax.swing.JButton();
        jButton2_Limpar = new javax.swing.JButton();
        jButton3_Cancelar = new javax.swing.JButton();
        jButton4_Consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bring Out The Cake - Confeitaria");
        setResizable(false);

        jLabel1_Tela_Cadastro_Cliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1_Tela_Cadastro_Cliente.setText("Cadastro de Cliente");

        jPanel2_Cadastro_Cliente.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2_Cadastro_Cliente.setPreferredSize(new java.awt.Dimension(780, 410));

        jLabel1_Email.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_Email.setText("E-mail:");
        jLabel1_Email.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField1_Email.setToolTipText("");

        jLabel2_Tipo_Pessoa.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2_Tipo_Pessoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2_Tipo_Pessoa.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_Tipo_Pessoa.setText("Tipo Pessoa:");
        jLabel2_Tipo_Pessoa.setPreferredSize(new java.awt.Dimension(55, 25));

        jComboBox1_Tipo_Pessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Jurídica" }));
        jComboBox1_Tipo_Pessoa.setToolTipText("");

        jLabel3_CPF.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3_CPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3_CPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_CPF.setText("CPF:");
        jLabel3_CPF.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField3_CPF.setToolTipText("");

        jLabel4_Nome.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4_Nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4_Nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_Nome.setText("Nome:");
        jLabel4_Nome.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField4_Nome.setToolTipText("");

        jLabel5_Sobrenome.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5_Sobrenome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5_Sobrenome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_Sobrenome.setText("Sobrenome:");
        jLabel5_Sobrenome.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField5_Sobrenome.setToolTipText("");

        jLabel6_CNPJ.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6_CNPJ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6_CNPJ.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_CNPJ.setText("CNPJ:");
        jLabel6_CNPJ.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField6_CNPJ.setToolTipText("");

        jLabel7_Razão_Social.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7_Razão_Social.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7_Razão_Social.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7_Razão_Social.setText("Razão Social:");
        jLabel7_Razão_Social.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField7_Razão_Social.setToolTipText("");

        jLabel8_Nome_Fantasia.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8_Nome_Fantasia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8_Nome_Fantasia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8_Nome_Fantasia.setText("Nome Fantasia:");
        jLabel8_Nome_Fantasia.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField8_Nome_Fantasia.setToolTipText("");

        jLabel9_Rua.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9_Rua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9_Rua.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9_Rua.setText("Rua:");
        jLabel9_Rua.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField9_Rua.setToolTipText("");

        jLabel10_Número.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10_Número.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10_Número.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10_Número.setText("Número:");
        jLabel10_Número.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField10_Número.setToolTipText("");

        jLabel11_Complemento.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11_Complemento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11_Complemento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11_Complemento.setText("Complemento:");
        jLabel11_Complemento.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField11_Complemento.setToolTipText("");

        jLabel12_Bairro.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12_Bairro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12_Bairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12_Bairro.setText("Bairro:");
        jLabel12_Bairro.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField12_Bairro.setToolTipText("");

        jLabel13_Cidade.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13_Cidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13_Cidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13_Cidade.setText("Cidade:");
        jLabel13_Cidade.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField13_Cidade.setToolTipText("");

        jLabel14_Estado.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14_Estado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14_Estado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14_Estado.setText("Estado:");
        jLabel14_Estado.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField14_Estado.setToolTipText("");

        jLabel15_CEP.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15_CEP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15_CEP.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15_CEP.setText("CEP:");
        jLabel15_CEP.setPreferredSize(new java.awt.Dimension(55, 25));

        jTextField15_CEP.setToolTipText("");

        jButton1_Salvar.setText("Salvar");
        jButton1_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_SalvarActionPerformed(evt);
            }
        });

        jButton2_Limpar.setText("Limpar");

        jButton3_Cancelar.setText("Cancelar");

        jButton4_Consultar.setText("Consultar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Telefone:");

        javax.swing.GroupLayout jPanel2_Cadastro_ClienteLayout = new javax.swing.GroupLayout(jPanel2_Cadastro_Cliente);
        jPanel2_Cadastro_Cliente.setLayout(jPanel2_Cadastro_ClienteLayout);
        jPanel2_Cadastro_ClienteLayout.setHorizontalGroup(
            jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                        .addComponent(jLabel3_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                            .addComponent(jLabel9_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9_Rua))
                        .addComponent(jLabel14_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                            .addComponent(jLabel10_Número, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField10_Número, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField11_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                    .addComponent(jLabel13_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField13_Cidade))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField14_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel15_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField15_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField12_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                        .addComponent(jButton1_Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4_Consultar))
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                    .addComponent(jLabel1_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1_Email))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                    .addComponent(jLabel5_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField5_Sobrenome))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                    .addComponent(jLabel4_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField4_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                .addComponent(jLabel2_Tipo_Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1_Tipo_Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8_Nome_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7_Razão_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField7_Razão_Social, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(jTextField8_Nome_Fantasia)))
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2_Cadastro_ClienteLayout.setVerticalGroup(
            jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1_Email)
                    .addComponent(jLabel1_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2_Tipo_Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1_Tipo_Pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3_CPF)
                                    .addComponent(jLabel3_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4_Nome)
                                    .addComponent(jLabel4_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel2_Cadastro_ClienteLayout.createSequentialGroup()
                                .addComponent(jLabel6_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7_Razão_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7_Razão_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5_Sobrenome)
                            .addComponent(jLabel5_Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel8_Nome_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8_Nome_Fantasia)))
                    .addComponent(jTextField6_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 28, Short.MAX_VALUE)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9_Rua)
                    .addComponent(jLabel9_Rua, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11_Complemento, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10_Número, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10_Número)
                        .addComponent(jTextField11_Complemento)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13_Cidade)
                    .addComponent(jLabel12_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12_Bairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14_Estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15_CEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2_Cadastro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Salvar)
                    .addComponent(jButton2_Limpar)
                    .addComponent(jButton3_Cancelar)
                    .addComponent(jButton4_Consultar))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_Tela_Cadastro_Cliente)
                    .addComponent(jPanel2_Cadastro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_Tela_Cadastro_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2_Cadastro_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_SalvarActionPerformed
        boolean sucesso;
        try {
            ClienteController clienteController = new ClienteController();
            sucesso = clienteController.cadastrarCliente(jTextField1_Email.getText(), jTextField9_Rua.getText(), 
                                                jTextField10_Número.getText(), jTextField11_Complemento.getText(), 
                                                jTextField12_Bairro.getText(), jTextField13_Cidade.getText(), jTextField14_Estado.getText(),
                                                jTextField15_CEP.getText());
            if (sucesso == true) {
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso.");                
            }
            else {
                JOptionPane.showMessageDialog(null, "Cadastrado não realizado."); 
            }
            
        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex);
        }       
    }//GEN-LAST:event_jButton1_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Salvar;
    private javax.swing.JButton jButton2_Limpar;
    private javax.swing.JButton jButton3_Cancelar;
    private javax.swing.JButton jButton4_Consultar;
    private javax.swing.JComboBox<String> jComboBox1_Tipo_Pessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10_Número;
    private javax.swing.JLabel jLabel11_Complemento;
    private javax.swing.JLabel jLabel12_Bairro;
    private javax.swing.JLabel jLabel13_Cidade;
    private javax.swing.JLabel jLabel14_Estado;
    private javax.swing.JLabel jLabel15_CEP;
    private javax.swing.JLabel jLabel1_Email;
    private javax.swing.JLabel jLabel1_Tela_Cadastro_Cliente;
    private javax.swing.JLabel jLabel2_Tipo_Pessoa;
    private javax.swing.JLabel jLabel3_CPF;
    private javax.swing.JLabel jLabel4_Nome;
    private javax.swing.JLabel jLabel5_Sobrenome;
    private javax.swing.JLabel jLabel6_CNPJ;
    private javax.swing.JLabel jLabel7_Razão_Social;
    private javax.swing.JLabel jLabel8_Nome_Fantasia;
    private javax.swing.JLabel jLabel9_Rua;
    private javax.swing.JPanel jPanel2_Cadastro_Cliente;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10_Número;
    private javax.swing.JTextField jTextField11_Complemento;
    private javax.swing.JTextField jTextField12_Bairro;
    private javax.swing.JTextField jTextField13_Cidade;
    private javax.swing.JTextField jTextField14_Estado;
    private javax.swing.JTextField jTextField15_CEP;
    private javax.swing.JTextField jTextField1_Email;
    private javax.swing.JTextField jTextField3_CPF;
    private javax.swing.JTextField jTextField4_Nome;
    private javax.swing.JTextField jTextField5_Sobrenome;
    private javax.swing.JTextField jTextField6_CNPJ;
    private javax.swing.JTextField jTextField7_Razão_Social;
    private javax.swing.JTextField jTextField8_Nome_Fantasia;
    private javax.swing.JTextField jTextField9_Rua;
    // End of variables declaration//GEN-END:variables
}
