/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confeitaria.view;

/**
 *
 * @author Max
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Pedido = new javax.swing.JMenu();
        jMenuItem1_1_Criar_Pedido = new javax.swing.JMenuItem();
        jMenuItem1_2_Visualizar_Pedido = new javax.swing.JMenuItem();
        jMenuItem1_3_Histórico_Pedidos = new javax.swing.JMenuItem();
        jMenu2_Cliente = new javax.swing.JMenu();
        jMenuItem2_1_Lista_Clientes = new javax.swing.JMenuItem();
        jMenuItem2_2_Cadastrar_Clientes = new javax.swing.JMenuItem();
        jMenu3_Logística = new javax.swing.JMenu();
        jMenu3_1_Produtos = new javax.swing.JMenu();
        jMenuItem3_1_2_Cadastro_Produtos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bring Out The Cake - Confeitaria");

        jMenu1_Pedido.setText("Pedido");

        jMenuItem1_1_Criar_Pedido.setText("Criar Pedido");
        jMenu1_Pedido.add(jMenuItem1_1_Criar_Pedido);

        jMenuItem1_2_Visualizar_Pedido.setText("Visualizar Pedido");
        jMenu1_Pedido.add(jMenuItem1_2_Visualizar_Pedido);

        jMenuItem1_3_Histórico_Pedidos.setText("Histórico de Pedidos");
        jMenu1_Pedido.add(jMenuItem1_3_Histórico_Pedidos);

        jMenuBar1.add(jMenu1_Pedido);

        jMenu2_Cliente.setText("Cliente");

        jMenuItem2_1_Lista_Clientes.setText("Lista de Clientes");
        jMenu2_Cliente.add(jMenuItem2_1_Lista_Clientes);

        jMenuItem2_2_Cadastrar_Clientes.setText("Cadastrar Clientes");
        jMenu2_Cliente.add(jMenuItem2_2_Cadastrar_Clientes);

        jMenuBar1.add(jMenu2_Cliente);

        jMenu3_Logística.setText("Logística");

        jMenu3_1_Produtos.setText("Produtos");

        jMenuItem3_1_2_Cadastro_Produtos.setText("Cadastro de Produtos");
        jMenu3_1_Produtos.add(jMenuItem3_1_2_Cadastro_Produtos);

        jMenu3_Logística.add(jMenu3_1_Produtos);

        jMenuBar1.add(jMenu3_Logística);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1_Pedido;
    private javax.swing.JMenu jMenu2_Cliente;
    private javax.swing.JMenu jMenu3_1_Produtos;
    private javax.swing.JMenu jMenu3_Logística;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_1_Criar_Pedido;
    private javax.swing.JMenuItem jMenuItem1_2_Visualizar_Pedido;
    private javax.swing.JMenuItem jMenuItem1_3_Histórico_Pedidos;
    private javax.swing.JMenuItem jMenuItem2_1_Lista_Clientes;
    private javax.swing.JMenuItem jMenuItem2_2_Cadastrar_Clientes;
    private javax.swing.JMenuItem jMenuItem3_1_2_Cadastro_Produtos;
    // End of variables declaration//GEN-END:variables
}
